INSERT INTO `balitas`(`nama`)
VALUES
('M. Rizki Pamungkas')
,('Zavier Akhtar')
,('Mikayla Inara S')
,('Earlita Arsyifa S')
,('Nahla Dwi Azzahra')
,('Nadia alysha')
,('M. Alfan')
,('M. Rifki Afriansyah')
,('M.Randika maulana')
,('A. Shaka Arkan N')
,('Aprilia Putri Yasmin')
,('Moch Dzaki Banu')
,('Arsya Evano F')
,('Alfarezel Maulid A')
,('Kayla Nadifa Almaira')
,('M. Jafar Shodiq')
,('Abdullah Farich')
,('Feliciya Adinda D')
,('M. Abiyan Aska P')
,('Dhea Ameera')
,('Avrilia Jasmine')
,('A. Ibnu Athaillah')
,('Adzqiara Yumna Q')
,('A. Aji Putra Bayu')
,('Ghania Inayah')
,('Dianita Lestari P')
,('Khaled')
,('M. Gibran')
,('Hamza')
,('Daviandra')
,('Azmi Abi Manaf A')
,('Mikayla Salsabila P')
,('Kyara Sachio N')
,('Devano Fabyan A')
,('Usama Bin Agus')
,('Shintia Rahma')
,('Areta Zaiba')
,('M. Jefri Pratama')
,('Nabila Putri S')
,('Tarendra Putra S')
,('Ardana Abi Putra')
,('Devan Farelia Elzafi')
,('Diva Permata Safina')
,('M.tengku maulana I')
,('Arfan')
,('Khansa Adelia N')
,('Moch Rafi Alana')
,('M. Ridho')
,('A. Isham Malabi')
,('Moch Hanif Haidar')


