INSERT INTO `balitas`(`nama`)
VALUES
('Ammar Fathee Karim'),
('Aqlan Harith Ridauddin'),
('Ararya Saguna Amrullah'),
('Arroyyan Dylan Alfarizqi'),
('Bari Abdul Jalil'),
('Basil Basyiruddin'),
('Beryl Hamizan Rabbani'),
('Billal Hafizh Athaillah'),
('Bakir Ahsan Amal'),
('Basith Taufiq Rahman'),
('Gafi Fazal Ilario'),
('Gaishan Raffasya Hafis'),
('Ghazaly Ibni Dzakir'),
('Ghifari Syafi Muzakki'),
('Ghibran Naufal Rizal'),
('Ezar Zhafar Dhiaurrahman'),
('Faal Hasam Ismam'),
('Faris Miqdad Nazeeh'),
('Farras Barra Muayyad'),
('Habib Hasyim Husaini'),
('Habibi Qurrotu Aini'),
('Hadwan Harsa Haryaka'),
('Hadza Masy’alul Ibad'),
('Hafizh Syadi Ismallah'),


('Adiva Arsyila Savina'),
('Adzkiya Naila Taleetha'),
('Syazani Nur Albirru'),
('Alia Shakeela Zanitha'),
('Alifa Zahra Fitriani'),
('Alzan Zea Sadiya'),
('Alzan Faeqa Amanda'),
('Alifia Rahmawati Fazila'),
('Amel Mahfuz Fariha'),
('Aminta Arles Fayda'),
('Andyra Naifa Habbaba')

